"""Export SM_VoxelDwarf_Miner01 from the .blend to a GLB.

ONE COMMAND, from the repo root:

    blender --background src-assets/blender/SM_VoxelDwarf_Miner01.blend \
            --python src-assets/blender/export_dwarf.py

Writes src-assets/export/SM_VoxelDwarf_Miner01.glb (gitignored scratch). The
runtime slot assets/gltf/ is promoted by the operator and is never written here.

WHY THIS EXISTS. From round 4 the .blend is the SOURCE OF TRUTH and this script is
the only sanctioned way to get a binary out of it. The older finishing condition --
"the committed generator regenerates the committed GLB exactly" -- retired with that
change: a hand-modelled mesh cannot be regenerated byte-identically from a script,
and faking it by dumping tables would be a lie. What replaces it is this: the export
is repeatable from the committed .blend, and check_asset.py plus the r4 revision
token police the result.

WHAT IT ENFORCES, because the .blend is authored part-by-part and the contract wants
one object:
  * every mesh part is joined into ONE mesh, ONE material, ONE palette image;
  * the figure is centred in Blender X and Y and set to min Z = 0, which after the
    Z-up -> Y-up conversion is the contract's "min Y = 0, centred in X and Z";
  * sockets, cameras and lights never reach the GLB;
  * the mesh is fit to rig and ship -- no n-gons, manifold, no loose or degenerate
    geometry, consistent winding, UVs present, and at most
    TRI_BUDGET triangles. The style clauses (axis-aligned, then flat-and-planar) were
    both lifted by Wolf on 2026-09-12: shading and curvature are the artist's call;
  * the object and mesh datablocks carry the revision, so a stale binary announces
    itself. The revision lives in the datablock names INSIDE the .blend, not in any
    filename -- there is exactly one place to bump it;
  * from round 8 it also carries the RIG: the skin is exported, the 19 joint names
    are read back out of the written file, and weights must be rigid (one joint per
    vertex at 1.0). An unrigged figure still exports, and says so.

WHAT IT CHECKS ON THE ARTIFACT RATHER THAN ON THE SCENE, because both of these have
already shipped a silent failure: the texture must be present in the GLB (round 7's
was dropped entirely, and the report line printed the datablock name anyway), and the
figure's seating is asserted from the GLB's own POSITION bounds (the scene-measured
line read min Z 0.000000 while the file carried geometry 0.75 m off the floor).
"""

import json
import math
import os
import struct
import sys

import bmesh
import bpy
from mathutils import Matrix, Vector

REV = "r14"        # each round bumps this, and it is the ONLY line to change here
ASSET = "SM_VoxelDwarf_Miner01"
COLLECTION = f"{ASSET}_{REV}"
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "export")
OUT_PATH = os.path.join(OUT_DIR, f"{ASSET}.glb")
# LOD0 ceiling, a build gate since round 7. Moved 4,000 -> 30,000 on 2026-09-13 by Wolf's ruling
# ("we can also increase the budget ... it's easier to optimize than add more details later on").
# The 4,000 was a row in the model sheet's DERIVED LOD ladder, which the 2026-09-11 ruling had
# explicitly made non-binding, and round 7 promoted it to a gate -- where it became the thing
# capping the figure's resolution. 30,000 is the top of the band tech-art-guidelines.md already
# records for a 96-voxel-equivalent dwarf, and the r3 dwarf shipped and ran at 14,398. The ladder's
# crowd argument (20 dwarves ~ 2x the terrain) constrains LOD1 and LOD2, not LOD0: a gameplay dwarf
# is 8.74 px, so the crowd never draws LOD0. This gate's job is now to catch a MISTAKE -- an
# unapplied subdivision, a mirrored duplicate, a cull that never ran -- not to shape the art.
#
# 2026-09-14, Wolf: "I want actually remove all limitations .. let's push and then optimize".
# 100,000 because round 12 proved a ceiling is not what shapes this figure: it used 19,064 of
# 30,000 and left the headroom unused, then inflated with 16,106 chamfer slivers of median width
# 1.32 mm to reach the *expected* count its brief printed. A gate the art cannot reach cannot
# cap the art. LOD and decimation come after the look is signed off; the runtime slot still
# carries r8 at 3,955 tris, so nothing in the game pays for a heavy source asset.
TRI_BUDGET = 100000
AREA_EPS_M2 = 1e-10   # a face smaller than this is degenerate, not geometry
WEIGHT_EPS = 1e-4     # a weight below this is nothing; a rigid weight is 1.0
# Blender's own FACE-domain attributes, which are not feature tags and must not be reported as
# such. `sharp_face` in particular exists on any mesh with a hard edge, so every figure would
# otherwise report one tag it never authored.
BUILTIN_FACE_ATTRS = frozenset(("material_index", "sharp_face", "custom_normal"))
# The 19 joints, fixed since round 3 and not the exporter's to negotiate. They are a SET here:
# the hierarchy is the artist's, the names are the contract, because the game binds by name.
JOINTS = frozenset((
    "root", "hips", "spine", "chest", "neck", "head",
    "shoulder.L", "shoulder.R", "elbow.L", "elbow.R", "hand.L", "hand.R",
    "hip.L", "hip.R", "knee.L", "knee.R", "foot.L", "foot.R",
    "beard",
))


def parts():
    """Every mesh part of the figure, in a stable order."""
    coll = bpy.data.collections.get(COLLECTION)
    if coll is None:
        raise SystemExit(f"export: collection {COLLECTION!r} not found in this .blend")
    found = sorted((o for o in coll.objects if o.type == 'MESH'), key=lambda o: o.name)
    if not found:
        raise SystemExit(f"export: collection {COLLECTION!r} holds no mesh parts")
    return found


def armature():
    """The one armature in the collection, or None while the figure is still unrigged.

    Optional on purpose: round 8 paints before it rigs, and an exporter that demanded a skeleton
    would fail every export taken during the modelling half of the session. What is NOT optional
    is silence -- the report line says `rig` either way, so an unrigged export announces itself.
    """
    found = [o for o in bpy.data.collections[COLLECTION].objects if o.type == 'ARMATURE']
    if len(found) > 1:
        raise SystemExit("export: %d armatures in %r; the figure takes one skeleton"
                         % (len(found), COLLECTION))
    return found[0] if found else None


def check_rig(ob, arm):
    """The two rig properties a machine can honestly check: the names, and rigid weights.

    Wolf's ruling from round 3 stands -- ONE mesh, RIGID weights, no soft skinning -- so every
    vertex belongs to exactly one joint at weight 1.0. Soft weights would not fail to render;
    they would quietly smooth the joints of a hard-edged figure, which is the kind of defect that
    only shows up once something is animated.

    ONLY BONE-NAMED GROUPS ARE WEIGHTS. A vertex group whose name is not a bone is a TAG, not a
    weight: from round 9 the features are carved into one continuous mesh and named with vertex
    groups (or face attributes) so the per-person combination layer can still find them --
    Wolf's point, 2026-09-13, and both mechanisms survive the exporter's join. Judged over every
    group, a vertex carrying `head` at 1.0 plus `feature_nose` at 1.0 read as SOFT-WEIGHTED and
    failed the build, which would have pushed the seat to delete its own feature tags to get an
    export. `feature_tags` reports them instead, and is deliberately not a gate.
    """
    names = {bone.name for bone in arm.data.bones}
    groups = {group.index: group.name for group in ob.vertex_groups}
    deform = {index for index, name in groups.items() if name in names}
    unweighted = soft = 0
    for vertex in ob.data.vertices:
        weights = [g for g in vertex.groups if g.weight > WEIGHT_EPS and g.group in deform]
        if not weights:
            unweighted += 1
        elif len(weights) > 1 or abs(weights[0].weight - 1.0) > WEIGHT_EPS:
            soft += 1
    return {
        "joints": len(names),
        "missing joints": len(JOINTS - names),
        "unexpected joints": len(names - JOINTS),
        "unweighted verts": unweighted,
        "soft-weighted verts": soft,
    }


def quantise_weights(ob, arm):
    """Snap each vertex to its dominant joint at 1.0, and refuse the ones with no dominant joint.

    The contract is RIGID weights, and a live Subdivision -- now the sanctioned way to reach the
    resolution floor -- interpolates them: a new vertex on an edge between a `spine` vertex and a
    `chest` vertex is born 0.5 / 0.5. Round 9 with a level-1 subdivision had 348 such vertices, all
    at the joint rings, all mechanical. They are snapped here, deterministically, and the count is
    printed so it is never silent.

    A vertex whose strongest joint carries less than half its weight is a different thing -- a
    genuinely soft paint job -- and that still fails the rig gate as soft-weighted, because snapping
    it would hide a decision the artist made.
    """
    bones = {bone.name for bone in arm.data.bones}
    deform = {g.index for g in ob.vertex_groups if g.name in bones}
    snapped = 0
    for vertex in ob.data.vertices:
        weights = [(g.weight, g.group) for g in vertex.groups
                   if g.group in deform and g.weight > WEIGHT_EPS]
        if len(weights) < 2:
            continue
        weight, group = max(weights)
        if weight < 0.5:
            continue
        for _w, other in weights:
            ob.vertex_groups[other].remove([vertex.index])
        ob.vertex_groups[group].add([vertex.index], 1.0, 'REPLACE')
        snapped += 1
    return snapped


def feature_tags(ob, arm):
    """The non-bone names by which a feature can be found inside the one mesh.

    Vertex groups and FACE-domain attributes both survive the join; Blender's face maps do not
    exist any more (removed in 4.x, verified absent in 5.2). Reported, never gated -- an untagged
    figure is not a broken export, it is a figure the combination layer cannot take apart yet.
    """
    bones = {bone.name for bone in arm.data.bones} if arm else set()
    groups = sorted(g.name for g in ob.vertex_groups if g.name not in bones)
    attributes = sorted(
        a.name for a in ob.data.attributes
        if a.domain == 'FACE' and not a.name.startswith('.') and a.name not in BUILTIN_FACE_ATTRS
    )
    return groups, attributes


def flatten(originals):
    """Copy every part, apply its modifiers, drop its socket parenting, and join the copies.

    THE MODIFIERS MUST BE APPLIED PER COPY, BEFORE THE JOIN. `object.join()` keeps only the active
    object's modifier stack, so a Subdivision on any part but the first was silently discarded --
    the export reported `live modifiers r8_torso:SUBSURF` and wrote a GLB with no subdivision in
    it. Found 2026-09-13 on a fixture built for exactly this workflow, and it is the third defect
    of this shape in this file: a line that describes the scene while the file says otherwise.

    An Armature modifier is removed rather than applied -- applying it bakes the rest pose into the
    vertices and throws the skin away. `main` re-binds the skin after the join.
    """
    bpy.ops.object.select_all(action='DESELECT')
    copies = []
    for ob in originals:
        dup = ob.copy()
        dup.data = ob.data.copy()
        dup.matrix_world = ob.matrix_world.copy()   # bake the socket transform in
        dup.parent = None
        bpy.context.scene.collection.objects.link(dup)
        for modifier in [m for m in dup.modifiers if m.type == 'ARMATURE']:
            dup.modifiers.remove(modifier)
        if dup.modifiers:
            bpy.context.view_layer.objects.active = dup
            bpy.ops.object.select_all(action='DESELECT')
            dup.select_set(True)
            bpy.ops.object.convert(target='MESH')
        copies.append(dup)
    bpy.ops.object.select_all(action='DESELECT')

    for dup in copies:
        dup.select_set(True)
    bpy.context.view_layer.objects.active = copies[0]
    bpy.ops.object.join()

    joined = bpy.context.view_layer.objects.active
    joined.name = f"{ASSET}_{REV}"
    joined.data.name = f"{ASSET}_{REV}"
    return joined


def seat_on_origin(ob):
    """Centre in X and Y, stand on Z = 0 -- the contract's invariant, in Blender axes.

    The object's own transform is BAKED INTO the vertices first, which the contract wants anyway
    (its transform clause requires an applied identity transform on the published node).

    It has to be baked rather than zeroed. This measured the bounds in WORLD space, added the
    shift to LOCAL vertex coordinates, and then set `ob.location` to zero -- three spaces, and
    the arithmetic is only right when the object transform is already identity. It was, for the
    r7 figure. It is not for any part placed with `primitive_cube_add(location=...)`, and the
    failure is silent both ways: the export line below prints the world bounds measured BEFORE
    the location was discarded, so it read `min Z 0.000000` while the GLB carried geometry
    0.75 m off the floor. Found 2026-09-13 on a rigged fixture, before round 8 could hit it.
    """
    bpy.context.view_layer.update()
    matrix = ob.matrix_world.copy()
    for v in ob.data.vertices:
        v.co = matrix @ v.co
    ob.matrix_world = Matrix.Identity(4)
    bpy.context.view_layer.update()

    # The bounds come from the EVALUATED mesh and the shift is applied to the CAGE. Catmull-Clark
    # pulls the surface inside its cage, so a figure seated on cage bounds would export floating
    # above the floor -- and the GLB-bounds gate in main() would (correctly) fail the build.
    evaluated = evaluated_mesh(ob)
    lo = Vector((1e9, 1e9, 1e9))
    hi = Vector((-1e9, -1e9, -1e9))
    for v in evaluated.vertices:
        lo = Vector(min(lo[i], v.co[i]) for i in range(3))
        hi = Vector(max(hi[i], v.co[i]) for i in range(3))
    ob.to_mesh_clear()
    shift = Vector((-(lo.x + hi.x) / 2.0, -(lo.y + hi.y) / 2.0, -lo.z))
    for v in ob.data.vertices:
        v.co = v.co + shift
    bpy.context.view_layer.update()
    return lo + shift, hi + shift, shift


def evaluated_mesh(ob):
    """The mesh the GLB will actually CARRY -- modifiers evaluated, as `export_apply=True` does.

    Added 2026-09-13 because the old measurements read the cage. With a live Subdivision or Bevel
    modifier the printed triangle count was the un-subdivided figure while the file carried the
    subdivided one, the topology gates inspected geometry that was never exported, and the
    "unapplied modifiers" gate then failed the build rather than let any of that ship. The three
    together made an iterative block-out-then-refine workflow impossible: every modifier had to be
    applied before the figure could be exported at all, so a subdivision cage could never be kept
    live and adjusted.

    Measure the evaluated mesh and all three problems go away at once -- the count is honest, the
    gates inspect the artifact, and modifiers become a reported fact instead of a failure. The
    caller must `to_mesh_clear()` the object it passed.
    """
    depsgraph = bpy.context.evaluated_depsgraph_get()
    return ob.evaluated_get(depsgraph).to_mesh()


def triangles(ob):
    """The REAL triangle count, from Blender's own triangulation.

    This was `len(polygons) * 2`, which assumes every face is a quad. That was true
    while the model was boxes and silently under-reports the moment topology is mixed
    -- which is exactly when a triangle budget starts mattering. Round 7 makes the
    budget a build gate, so the count has to be the one the GLB will carry.
    """
    me = evaluated_mesh(ob)
    me.calc_loop_triangles()
    count = len(me.loop_triangles)
    ob.to_mesh_clear()
    return count


def check_topology(ob, originals):
    """The game-mesh guarantee that replaced the style clauses on 2026-09-12.

    Wolf's ruling lifted flat faces, flat shading, bevels, subdivision and smooth
    normals -- none of them is tested any more, and rotation never was the thing that
    guarded the look. What stays is what a mesh needs in order to be rigged, skinned
    and shipped, plus the triangle budget.

    Deliberately NOT tested, because no cheap test is honest: interior geometry, and
    UV island overlap. Both are review items, judged by eye. A gate that cannot
    actually detect its subject is worse than no gate -- it certifies.
    """
    me = evaluated_mesh(ob)
    bm = bmesh.new()
    bm.from_mesh(me)

    ngons = sum(1 for f in bm.faces if len(f.verts) > 4)
    loose_verts = sum(1 for v in bm.verts if not v.link_edges)
    loose_edges = sum(1 for e in bm.edges if not e.link_faces)
    nonmanifold = sum(1 for e in bm.edges if len(e.link_faces) > 2)
    degenerate = sum(1 for f in bm.faces if f.calc_area() < AREA_EPS_M2)

    # Two faces sharing an edge must traverse it in OPPOSITE directions. If they
    # traverse it the same way, one of them is wound backwards.
    flipped = 0
    for e in bm.edges:
        if len(e.link_faces) != 2:
            continue
        walked = []
        for f in e.link_faces:
            for lp in f.loops:
                if lp.edge is e:
                    walked.append((lp.vert.index, lp.link_loop_next.vert.index))
                    break
        if len(walked) == 2 and walked[0] == walked[1]:
            flipped += 1

    bm.free()
    uv_layers = len(me.uv_layers)
    ob.to_mesh_clear()

    return {
        "n-gons": ngons,
        "non-manifold edges": nonmanifold,
        "loose verts": loose_verts,
        "loose edges": loose_edges,
        "degenerate faces": degenerate,
        "flipped winding": flipped,
        "missing UV layer": 0 if uv_layers else 1,
    }


def modifier_summary(originals):
    """Which modifiers are live, as a fact to report rather than a build failure.

    This was a GATE, and it had to be while the counts above read the cage: an unapplied
    Subdivision made the triangle figure a lie. The counts read the evaluated mesh now, so a live
    modifier is honest -- and forbidding them forbade the block-out-then-refine workflow. An
    Armature modifier was always correct to have; applying it would bake the rest pose into the
    vertices and throw the skin away.
    """
    live = [(o.name, m.type) for o in originals for m in o.modifiers if m.type != 'ARMATURE']
    return live


def exposed_holes(ob):
    """Holes a camera can SEE, which is the only kind that is a defect.

    A boundary edge -- one face instead of two -- is a hole in the surface, and the topology gate
    above never counted them: it defines non-manifold as an edge with MORE than two faces. Round 10
    shipped a figure with 962 boundary edges, including the top of its head, and passed every gate
    clean. Round 9 had 18 and round 8 had 425.

    Which is why the count alone cannot be the gate. Round 8's 425 were DELIBERATE: its buried-face
    cull deletes faces that are sealed inside another mass, and deleting a face opens the shell
    where nothing can ever see it. Gating the count at zero would forbid that, so the test has to
    ask the question that actually matters -- can anything look in?

    For each boundary edge, rays leave the hole along its face's normal and along four directions
    tilted 30 degrees off it. The hole counts as exposed only if EVERY ray escapes without striking
    the figure again. One ray was not enough: a single normal grazing past a neighbouring surface
    reported two exposed holes on round 9's figure, which is a good figure, and a gate that fails a
    good figure becomes noise the moment someone has to ship. Five rays that all escape is a hole
    you can see into.

    Run against the JOINED mesh, so a hole in the body that the hair covers is correctly forgiven.
    Measured on three revisions, which is how the threshold was chosen:

        r9   18 boundary edges,  0 exposed   -- the figure Wolf accepted on form
        r8  425 boundary edges, 23 exposed   -- shipped; its own magenta-world check saw none of
                                                them, because it looked from three views
        r10 962 boundary edges, 58 exposed   -- "completely broken .. top of head is a hole"

    Validated against the observation rather than only against itself: r10's highest exposed holes
    sit in the hair at z = 1.13, the crown, which is exactly where Wolf said the hole was.
    """
    me = evaluated_mesh(ob)
    bm = bmesh.new()
    bm.from_mesh(me)
    bm.faces.ensure_lookup_table()
    exposed = boundary = 0
    for edge in bm.edges:
        if len(edge.link_faces) != 1:
            continue
        boundary += 1
        face = edge.link_faces[0]
        middle = (edge.verts[0].co + edge.verts[1].co) / 2.0
        normal = face.normal.normalized()
        along = (edge.verts[1].co - edge.verts[0].co).normalized()
        across = normal.cross(along).normalized()
        tilt = math.radians(30.0)
        fan = [normal]
        for axis in (along, across):
            for sign in (1.0, -1.0):
                fan.append(
                    (normal * math.cos(tilt) + axis * sign * math.sin(tilt)).normalized()
                )
        # Both directions: an inside-out shell's normal points INTO the shell, and a ray cast
        # that way hits the far wall and reports the hole as sealed. Exposed if EITHER fan
        # escapes whole -- a culled interior face is sealed both ways, a real hole is open one way.
        if any(all(not ob.ray_cast(middle + d * sign * 1e-4, d * sign)[0] for d in fan)
               for sign in (1.0, -1.0)):
            exposed += 1
    bm.free()
    ob.to_mesh_clear()
    return boundary, exposed


def inside_out(originals):
    """Masses whose shell faces inward -- negative signed volume on the evaluated mesh.

    The winding gate compares each edge's two faces with each other, so a shell that is inverted
    CONSISTENTLY passes it: every neighbour agrees, they are all wrong together. Round 10 shipped
    its moustache at -1.34 L and its straps at -2.93 L; with backface culling on, an inverted mass
    renders as its own inside. Round 9's ten masses are all positive.

    ONLY CLOSED MASSES ARE JUDGED. Signed volume means nothing on an open shell: round 8's culled
    parts read hem -11.5 L, fringe -7.6 L, skull -4.5 L, and none of them is inverted -- the faces
    that would have closed the integral were culled away. So a mass with any boundary edge is
    reported as open and left to the hole gate; once its holes are closed, this gate applies. The
    spec bans culling from round 11, so every mass is expected to arrive closed.
    """
    depsgraph = bpy.context.evaluated_depsgraph_get()
    wrong, open_shells = [], []
    for ob in originals:
        me = ob.evaluated_get(depsgraph).to_mesh()
        bm = bmesh.new()
        bm.from_mesh(me)
        if any(len(e.link_faces) == 1 for e in bm.edges):
            open_shells.append(ob.name)
        else:
            volume = bm.calc_volume(signed=True)
            if volume < 0:
                wrong.append((ob.name, volume * 1000.0))
        bm.free()
        ob.to_mesh_clear()
    return wrong, open_shells


def form_planes(originals, joined):
    """Planes of FORM, which is what a subdivision cannot add.

    Round 11 met the spec's resolution floor -- every mass at 16-23 mm median face edge -- by
    putting a SIMPLE subdivision on a 269-face cage. SIMPLE subdivision splits each face into four
    WITHOUT MOVING ANY VERTEX, so it is shape-preserving: measured on all ten of its masses, the
    evaluated volume equals the cage volume to 0.00 %. The figure was 269 faces of form wearing
    25,248 triangles, and its face region had SEVEN cage faces. That is my metric's fault, not the
    seat's: median face edge is satisfiable by dividing a featureless cage, and the seat hit the
    number honestly and said so in its report.

    Distinct face normals cannot be faked that way. A subdivided flat face contributes ONE normal
    however many pieces it is cut into, so this counts changes of direction in the surface -- which
    is what a viewer reads as detail. Measured across three revisions:

        r9   5,530 faces, 2,251 planes   -- coarse but the form Wolf liked
        r10 13,592 faces, 3,374 planes   -- the most detailed figure so far
        r11 12,624 faces,   374 planes   -- "solid" and nearly featureless

    2026-09-14: AND A BEVEL CAN FAKE IT, WHICH A SUBDIVISION COULD NOT. Round 12 met a 2,500 target
    with 3,288 planes, and its own report says how: the cage at 1,418 faces carried 111 planes, and
    a three-segment Bevel took it to 3,273. A chamfer genuinely faces a new direction, so this is
    not even cheating -- which is what made it a better trap than subdivision. Measured on the
    delivered GLB: 84.5 % of its triangles were chamfer strips carrying 9.6 % of the surface, at a
    MEDIAN WIDTH OF 1.32 mm, where the same spec had asked for chamfers of 8-26 mm.

    So the count is now taken ONLY on faces whose shortest edge is at least one source pixel of the
    reference. A face narrower than one reference pixel cannot be a feature of the reference, and a
    threshold in the reference's own units cannot drift with the art. This is immune to both cheap
    operations: subdivision splits a flat face and adds no normal, and a bevel sliver falls under
    the threshold. Re-measured across every round still recoverable from git:

        round   faces    PLANES   raw    slivers   the verdict it got
        r7         446      24      24      3 %     head one box, whole face one quad
        r8       2,120     441     445      7 %     "finally starts to look what it should"
        r9       5,530   1,436   2,156     49 %     the form Wolf liked
        r10     13,592   1,408   3,257     58 %     wrecked by its tooling, not its form
        r11     12,624     267     319     38 %     "not quite close to what I want"
        r12      9,752     143   3,292     85 %     "lacking detail .. boxy .. missing feet"

    The PLANES column tracks Wolf's eye in every round; the raw column INVERTS it -- r12 raw 3,292
    against r9's 2,156, for the figure he called the less detailed of the two. The gate is 1,200,
    below r9's 1,436 and far below the 3,000 round 13 targets, because its job is to catch a figure
    that LOST form rather than to become a target to tune against. The sliver fraction is printed
    beside it so inflation stays visible without being gated -- chamfers are wanted, at 8-26 mm.
    """
    depsgraph = bpy.context.evaluated_depsgraph_get()
    cage = 0
    for ob in originals:
        mirrored = 2 if any(m.type == 'MIRROR' for m in ob.modifiers) else 1
        cage += len(ob.data.polygons) * mirrored
    me = joined.evaluated_get(depsgraph).to_mesh()
    basis = joined.matrix_world.to_3x3()
    planes = set()
    raw = set()
    slivers = 0
    for face in me.polygons:
        normal = (basis @ face.normal).normalized()
        key = (round(normal.x, 2), round(normal.y, 2), round(normal.z, 2))
        raw.add(key)
        loop = [joined.matrix_world @ me.vertices[i].co for i in face.vertices]
        shortest = min((loop[i] - loop[i - 1]).length for i in range(len(loop)))
        if shortest >= SOURCE_PIXEL_M:
            planes.add(key)
        else:
            slivers += 1
    faces = len(me.polygons)
    joined.to_mesh_clear()
    return cage, faces, len(planes), len(raw), slivers


# One source pixel of the reference sheet: the figure spans 140 px for 1.200 m. A face narrower
# than this cannot be a feature of the reference, so it does not get to be a plane of form.
SOURCE_PIXEL_M = 1.200 / 140.0

# RETIRED FOR ROUND 14, on that round's sec.2: "The plane metric is retired ... If its form floor
# (1,200 planes) fails the build, set that one constant to 0 and say so." Round 14 is judged on
# silhouette against the ortho sheet, not on a plane count, and it builds the figure from ~110
# boxes rather than by carving -- 888 triangles against a floor that assumed a carved body. The
# count is still computed and still printed; nothing acts on it.
FORM_PLANE_FLOOR = 0


def glb_facts(path):
    """What the written GLB actually carries: its image names, and its skin's joint names.

    Read back out of the artifact.

    Round 7 shipped with image `r7` pointing at an absolute `D:/...` path and nothing packed, so
    off the authoring machine it resolved to nothing, the glTF exporter dropped the material's
    texture entirely -- no images, no textures, no samplers, no baseColorTexture -- and this
    script still printed `texture image r7` and exited 0, because that line reports the
    DATABLOCK'S NAME. A name is not data. The only honest subject for the gate is the file.
    """
    with open(path, "rb") as handle:
        data = handle.read()
    offset, images, joints, bounds = 12, [], [], (None, None)
    while offset + 8 <= len(data):
        length, kind = struct.unpack_from("<II", data, offset)
        if kind == 0x4E4F534A:
            document = json.loads(data[offset + 8:offset + 8 + length].decode("utf-8"))
            images = [image.get("name", "<unnamed>") for image in document.get("images", [])]
            primitive = document["meshes"][0]["primitives"][0]
            position = document["accessors"][primitive["attributes"]["POSITION"]]
            bounds = (position.get("min"), position.get("max"))
            nodes = document.get("nodes", [])
            joints = sorted(
                nodes[index].get("name", "<unnamed>")
                for skin in document.get("skins", [])
                for index in skin.get("joints", [])
            )
            break
        offset += 8 + length
    return images, joints, bounds


def main():
    for ob in list(bpy.data.objects):
        if ob.type in {'CAMERA', 'LIGHT'}:
            bpy.data.objects.remove(ob, do_unlink=True)

    if bpy.context.view_layer.objects.active is None:
        bpy.context.view_layer.objects.active = parts()[0]
    if bpy.context.object and bpy.context.object.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')

    arm = armature()
    originals = parts()
    for ob in originals:
        ob.hide_set(False)
        ob.hide_viewport = False
        ob.hide_render = False

    joined = flatten(originals)
    lo, hi, shift = seat_on_origin(joined)
    topology = check_topology(joined, originals)
    modifiers = modifier_summary(originals)
    tris = triangles(joined)
    boundary, exposed = exposed_holes(joined)
    cage_faces, eval_faces, planes, raw_planes, slivers = form_planes(originals, joined)

    # Re-bind the skin the join threw away, and move the skeleton by the SAME shift the vertices
    # took. `seat_on_origin` edits vertex coordinates; bones live in the armature, so without
    # this the joints sit wherever the figure used to be. `flatten` deliberately drops parenting
    # to bake the socket transforms, which is why the binding is remade here rather than kept.
    rig = None
    snapped = 0
    inverted, open_shells = inside_out(originals)
    if arm is not None:
        arm.location = arm.location + shift
        joined.modifiers.new("Armature", 'ARMATURE').object = arm
        bpy.context.view_layer.update()
        snapped = quantise_weights(joined, arm)
        rig = check_rig(joined, arm)
    tag_groups, tag_attributes = feature_tags(joined, arm)

    materials = {slot.material for slot in joined.material_slots if slot.material}
    images = {n.image for m in materials if m.use_nodes
              for n in m.node_tree.nodes if n.type == 'TEX_IMAGE' and n.image}

    # glTF CLAMP_TO_EDGE, which the asset contract's sampler clause asks for and a packed set of
    # UV islands needs: under Blender's default REPEAT the far edge of the map bleeds into an
    # island sitting on the border. Forced here rather than in the .blend so no future round can
    # author it away. Blender's 'EXTEND' is glTF's CLAMP_TO_EDGE.
    for material in materials:
        if not material.use_nodes:
            continue
        for node in material.node_tree.nodes:
            if node.type == 'TEX_IMAGE':
                node.extension = 'EXTEND'

    # only the joined object -- and the skeleton it is bound to -- reaches the exporter
    bpy.ops.object.select_all(action='DESELECT')
    joined.select_set(True)
    if arm is not None:
        arm.select_set(True)
    bpy.context.view_layer.objects.active = joined

    os.makedirs(OUT_DIR, exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=OUT_PATH,
        export_format='GLB',
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_materials='EXPORT',
        export_image_format='AUTO',
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_skins=True,
        export_animations=False,
    )

    embedded, joints, bounds = glb_facts(OUT_PATH)
    size = (hi.x - lo.x, hi.y - lo.y, hi.z - lo.z)
    print("")
    print("EXPORT %s" % OUT_PATH)
    print("  parts joined      %d -> 1 mesh %r" % (len(originals), joined.data.name))
    print("  object / mesh     %s / %s" % (joined.name, joined.data.name))
    print("  materials         %s" % ", ".join(sorted(m.name for m in materials)))
    print("  texture image     %s   in the GLB: %s"
          % (", ".join(sorted(i.name for i in images)) or "<none>",
             ", ".join(embedded) or "<NONE>"))
    print("  triangles         %d  of %d budget" % (tris, TRI_BUDGET))
    print("  size m (X,Y,Z)    %.3f x %.3f x %.3f" % size)
    print("  blender min Z     %.6f   (glTF min Y)" % lo.z)
    print("  blender centre XY %.6f, %.6f   (glTF centre X, Z)"
          % ((lo.x + hi.x) / 2.0, (lo.y + hi.y) / 2.0))
    print("  topology          %s"
          % "   ".join("%s %d" % (k, v) for k, v in topology.items()))
    print("  form              %d planes of form on faces >= %.1f mm, from %d cage faces -> "
          "%d faces (x%.1f)"
          % (planes, SOURCE_PIXEL_M * 1000.0, cage_faces, eval_faces,
             (float(eval_faces) / cage_faces) if cage_faces else 0.0))
    print("  slivers           %d of %d faces are narrower than one source pixel (%.1f%%); "
          "raw plane count %d"
          % (slivers, eval_faces, (100.0 * slivers / eval_faces) if eval_faces else 0.0,
             raw_planes))
    print("  holes             %d boundary edges, %d EXPOSED to the outside"
          % (boundary, exposed))
    print("  inside-out masses %s   (%d open shell%s not judged: %s)"
          % (", ".join("%s (%.2f L)" % row for row in inverted) or "none",
             len(open_shells), "" if len(open_shells) == 1 else "s",
             ", ".join(open_shells) or "-"))
    print("  feature tags      %d vertex groups, %d face attributes%s"
          % (len(tag_groups), len(tag_attributes),
             ("   " + ", ".join(tag_groups + tag_attributes)) if (tag_groups or tag_attributes) else ""))
    print("  live modifiers    %s"
          % (", ".join("%s:%s" % row for row in modifiers) or "none"))
    if rig is None:
        print("  rig               <NONE -- unrigged figure>")
    else:
        print("  rig               %s   joint names in the GLB: %s"
              % ("   ".join("%s %d" % (k, v) for k, v in rig.items()),
                 ", ".join(joints) or "<NONE>"))
        print("  weights snapped   %d interpolated vertices quantised to their dominant joint"
              % snapped)
    print("  GLB min/max       %s / %s   (glTF axes: X, Y up, Z)"
          % (bounds[0], bounds[1]))
    print("  bytes             %d" % os.path.getsize(OUT_PATH))

    # The seating clause, asserted on the ARTIFACT rather than on the intention. Every figure
    # above was measured in the scene; these are the numbers the exporter itself wrote into the
    # GLB's POSITION accessor, and they are what `check_asset.py` will read.
    if bounds[0] is None or bounds[1] is None:
        raise SystemExit("export: the GLB carries no POSITION bounds to check")
    low, high = bounds
    seating = {
        "min Y": low[1],
        "centre X": (low[0] + high[0]) / 2.0,
        "centre Z": (low[2] + high[2]) / 2.0,
    }
    off = {k: v for k, v in seating.items() if abs(v) > 1e-6}
    if off:
        raise SystemExit(
            "export: seating gate failed on the GLB's own bounds -- %s. The figure measured "
            "clean in the scene, so the geometry moved between the measurement and the file."
            % ", ".join("%s %.6f" % (k, v) for k, v in off.items()))

    if rig is not None:
        wrong = {k: v for k, v in rig.items() if k != "joints" and v}
        if wrong:
            raise SystemExit("export: rig gate failed -- %s"
                             % ", ".join("%s %d" % (k, v) for k, v in wrong.items()))
        if sorted(JOINTS) != joints:
            raise SystemExit(
                "export: the armature is correct and the GLB's skin is not -- joints in the "
                "file: %s. The skin is what the game binds to; a rig that stops at the .blend "
                "is not a rig." % (", ".join(joints) or "<NONE>"))

    if images and not embedded:
        raise SystemExit(
            "export: the material carries %d image(s) and the GLB embeds NONE -- the texture "
            "did not reach the artifact. The usual cause is an unpacked external path that does "
            "not resolve on this machine; pack it into the .blend (File > External Data > Pack "
            "Resources) so the source reproduces the export anywhere." % len(images))

    if planes < FORM_PLANE_FLOOR:
        raise SystemExit(
            "export: only %d planes of form (floor %d), counted on the %d faces at least one "
            "source pixel (%.1f mm) wide; %d of %d faces are narrower than that and do not count. "
            "The geometry is there -- what is missing is CHANGES OF DIRECTION a viewer can "
            "resolve. Neither a SIMPLE subdivision nor a 1 mm bevel can add one: the first splits "
            "faces without moving them, the second was measured at a 1.32 mm median on r12 and "
            "carried 9.6 %% of its surface. Put the detail in the cage. For scale: r9 has 1,436 "
            "planes and r12 had 143."
            % (planes, FORM_PLANE_FLOOR, eval_faces - slivers, SOURCE_PIXEL_M * 1000.0,
               slivers, eval_faces))
    if inverted:
        raise SystemExit(
            "export: inside-out mass -- %s. The shell faces inward, so with backface culling it "
            "renders as its own inside. Recalculate normals outward, and check the signed volume "
            "rather than trusting the winding gate, which cannot see a consistently inverted shell."
            % ", ".join("%s (%.2f L)" % row for row in inverted))
    if exposed:
        raise SystemExit(
            "export: %d of %d boundary edges are EXPOSED to the outside -- the figure has holes a "
            "camera can see. A boundary edge is only acceptable where another mass seals it (a "
            "buried-face cull does that on purpose); these are open. Close them or cover them."
            % (exposed, boundary))

    broken = {k: v for k, v in topology.items() if v}
    if broken:
        raise SystemExit("export: topology gate failed -- %s"
                         % ", ".join("%s %d" % (k, v) for k, v in broken.items()))
    if tris > TRI_BUDGET:
        raise SystemExit("export: %d triangles exceeds the %d budget" % (tris, TRI_BUDGET))


if __name__ == "__main__":
    main()
