"""Export SM_VoxelDwarf_Miner01 from the .blend to a GLB.

ONE COMMAND, from the repo root:

    blender --background src-assets/blender/SM_VoxelDwarf_Miner01.blend \
            --python src-assets/blender/export_dwarf.py

Writes src-assets/export/SM_VoxelDwarf_Miner01.glb (gitignored scratch). The
runtime slot assets/gltf/ is promoted by the operator and is never written here.

WHY THIS EXISTS. From round 4 the .blend is the SOURCE OF TRUTH and this script is
the only sanctioned way to get a binary out of it. The older finishing condition --
"the committed generator regenerates the committed GLB exactly" -- retired with that
change: a hand-modelled mesh cannot be regenerated byte-identically from a script,
and faking it by dumping tables would be a lie. What replaces it is this: the export
is repeatable from the committed .blend, and check_asset.py plus the r4 revision
token police the result.

WHAT IT ENFORCES, because the .blend is authored part-by-part and the contract wants
one object:
  * every mesh part is joined into ONE mesh, ONE material, ONE palette image;
  * the figure is centred in Blender X and Y and set to min Z = 0, which after the
    Z-up -> Y-up conversion is the contract's "min Y = 0, centred in X and Z";
  * sockets, cameras and lights never reach the GLB;
  * the mesh is fit to rig and ship -- no n-gons, manifold, no loose or degenerate
    geometry, consistent winding, UVs present, and at most
    TRI_BUDGET triangles. The style clauses (axis-aligned, then flat-and-planar) were
    both lifted by Wolf on 2026-09-12: shading and curvature are the artist's call;
  * the object and mesh datablocks carry the revision, so a stale binary announces
    itself. The revision lives in the datablock names INSIDE the .blend, not in any
    filename -- there is exactly one place to bump it;
  * from round 8 it also carries the RIG: the skin is exported, the 19 joint names
    are read back out of the written file, and weights must be rigid (one joint per
    vertex at 1.0). An unrigged figure still exports, and says so.

WHAT IT CHECKS ON THE ARTIFACT RATHER THAN ON THE SCENE, because both of these have
already shipped a silent failure: the texture must be present in the GLB (round 7's
was dropped entirely, and the report line printed the datablock name anyway), and the
figure's seating is asserted from the GLB's own POSITION bounds (the scene-measured
line read min Z 0.000000 while the file carried geometry 0.75 m off the floor).
"""

import json
import os
import struct
import sys

import bmesh
import bpy
from mathutils import Matrix, Vector

REV = "r9"        # each round bumps this, and it is the ONLY line to change here
ASSET = "SM_VoxelDwarf_Miner01"
COLLECTION = f"{ASSET}_{REV}"
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "export")
OUT_PATH = os.path.join(OUT_DIR, f"{ASSET}.glb")
# LOD0 ceiling, a build gate since round 7. Moved 4,000 -> 30,000 on 2026-09-13 by Wolf's ruling
# ("we can also increase the budget ... it's easier to optimize than add more details later on").
# The 4,000 was a row in the model sheet's DERIVED LOD ladder, which the 2026-09-11 ruling had
# explicitly made non-binding, and round 7 promoted it to a gate -- where it became the thing
# capping the figure's resolution. 30,000 is the top of the band tech-art-guidelines.md already
# records for a 96-voxel-equivalent dwarf, and the r3 dwarf shipped and ran at 14,398. The ladder's
# crowd argument (20 dwarves ~ 2x the terrain) constrains LOD1 and LOD2, not LOD0: a gameplay dwarf
# is 8.74 px, so the crowd never draws LOD0. This gate's job is now to catch a MISTAKE -- an
# unapplied subdivision, a mirrored duplicate, a cull that never ran -- not to shape the art.
TRI_BUDGET = 30000
AREA_EPS_M2 = 1e-10   # a face smaller than this is degenerate, not geometry
WEIGHT_EPS = 1e-4     # a weight below this is nothing; a rigid weight is 1.0
# The 19 joints, fixed since round 3 and not the exporter's to negotiate. They are a SET here:
# the hierarchy is the artist's, the names are the contract, because the game binds by name.
JOINTS = frozenset((
    "root", "hips", "spine", "chest", "neck", "head",
    "shoulder.L", "shoulder.R", "elbow.L", "elbow.R", "hand.L", "hand.R",
    "hip.L", "hip.R", "knee.L", "knee.R", "foot.L", "foot.R",
    "beard",
))


def parts():
    """Every mesh part of the figure, in a stable order."""
    coll = bpy.data.collections.get(COLLECTION)
    if coll is None:
        raise SystemExit(f"export: collection {COLLECTION!r} not found in this .blend")
    found = sorted((o for o in coll.objects if o.type == 'MESH'), key=lambda o: o.name)
    if not found:
        raise SystemExit(f"export: collection {COLLECTION!r} holds no mesh parts")
    return found


def armature():
    """The one armature in the collection, or None while the figure is still unrigged.

    Optional on purpose: round 8 paints before it rigs, and an exporter that demanded a skeleton
    would fail every export taken during the modelling half of the session. What is NOT optional
    is silence -- the report line says `rig` either way, so an unrigged export announces itself.
    """
    found = [o for o in bpy.data.collections[COLLECTION].objects if o.type == 'ARMATURE']
    if len(found) > 1:
        raise SystemExit("export: %d armatures in %r; the figure takes one skeleton"
                         % (len(found), COLLECTION))
    return found[0] if found else None


def check_rig(ob, arm):
    """The two rig properties a machine can honestly check: the names, and rigid weights.

    Wolf's ruling from round 3 stands -- ONE mesh, RIGID weights, no soft skinning -- so every
    vertex belongs to exactly one joint at weight 1.0. Soft weights would not fail to render;
    they would quietly smooth the joints of a hard-edged figure, which is the kind of defect that
    only shows up once something is animated.
    """
    names = {bone.name for bone in arm.data.bones}
    groups = {group.index: group.name for group in ob.vertex_groups}
    unweighted = soft = misnamed_groups = 0
    for vertex in ob.data.vertices:
        weights = [g for g in vertex.groups if g.weight > WEIGHT_EPS]
        if not weights:
            unweighted += 1
        elif len(weights) > 1 or abs(weights[0].weight - 1.0) > WEIGHT_EPS:
            soft += 1
        elif groups.get(weights[0].group) not in names:
            misnamed_groups += 1
    return {
        "joints": len(names),
        "missing joints": len(JOINTS - names),
        "unexpected joints": len(names - JOINTS),
        "unweighted verts": unweighted,
        "soft-weighted verts": soft,
        "verts weighted to a non-bone": misnamed_groups,
    }


def flatten(originals):
    """Copy every part, apply its modifiers, drop its socket parenting, and join the copies.

    THE MODIFIERS MUST BE APPLIED PER COPY, BEFORE THE JOIN. `object.join()` keeps only the active
    object's modifier stack, so a Subdivision on any part but the first was silently discarded --
    the export reported `live modifiers r8_torso:SUBSURF` and wrote a GLB with no subdivision in
    it. Found 2026-09-13 on a fixture built for exactly this workflow, and it is the third defect
    of this shape in this file: a line that describes the scene while the file says otherwise.

    An Armature modifier is removed rather than applied -- applying it bakes the rest pose into the
    vertices and throws the skin away. `main` re-binds the skin after the join.
    """
    bpy.ops.object.select_all(action='DESELECT')
    copies = []
    for ob in originals:
        dup = ob.copy()
        dup.data = ob.data.copy()
        dup.matrix_world = ob.matrix_world.copy()   # bake the socket transform in
        dup.parent = None
        bpy.context.scene.collection.objects.link(dup)
        for modifier in [m for m in dup.modifiers if m.type == 'ARMATURE']:
            dup.modifiers.remove(modifier)
        if dup.modifiers:
            bpy.context.view_layer.objects.active = dup
            bpy.ops.object.select_all(action='DESELECT')
            dup.select_set(True)
            bpy.ops.object.convert(target='MESH')
        copies.append(dup)
    bpy.ops.object.select_all(action='DESELECT')

    for dup in copies:
        dup.select_set(True)
    bpy.context.view_layer.objects.active = copies[0]
    bpy.ops.object.join()

    joined = bpy.context.view_layer.objects.active
    joined.name = f"{ASSET}_{REV}"
    joined.data.name = f"{ASSET}_{REV}"
    return joined


def seat_on_origin(ob):
    """Centre in X and Y, stand on Z = 0 -- the contract's invariant, in Blender axes.

    The object's own transform is BAKED INTO the vertices first, which the contract wants anyway
    (its transform clause requires an applied identity transform on the published node).

    It has to be baked rather than zeroed. This measured the bounds in WORLD space, added the
    shift to LOCAL vertex coordinates, and then set `ob.location` to zero -- three spaces, and
    the arithmetic is only right when the object transform is already identity. It was, for the
    r7 figure. It is not for any part placed with `primitive_cube_add(location=...)`, and the
    failure is silent both ways: the export line below prints the world bounds measured BEFORE
    the location was discarded, so it read `min Z 0.000000` while the GLB carried geometry
    0.75 m off the floor. Found 2026-09-13 on a rigged fixture, before round 8 could hit it.
    """
    bpy.context.view_layer.update()
    matrix = ob.matrix_world.copy()
    for v in ob.data.vertices:
        v.co = matrix @ v.co
    ob.matrix_world = Matrix.Identity(4)
    bpy.context.view_layer.update()

    # The bounds come from the EVALUATED mesh and the shift is applied to the CAGE. Catmull-Clark
    # pulls the surface inside its cage, so a figure seated on cage bounds would export floating
    # above the floor -- and the GLB-bounds gate in main() would (correctly) fail the build.
    evaluated = evaluated_mesh(ob)
    lo = Vector((1e9, 1e9, 1e9))
    hi = Vector((-1e9, -1e9, -1e9))
    for v in evaluated.vertices:
        lo = Vector(min(lo[i], v.co[i]) for i in range(3))
        hi = Vector(max(hi[i], v.co[i]) for i in range(3))
    ob.to_mesh_clear()
    shift = Vector((-(lo.x + hi.x) / 2.0, -(lo.y + hi.y) / 2.0, -lo.z))
    for v in ob.data.vertices:
        v.co = v.co + shift
    bpy.context.view_layer.update()
    return lo + shift, hi + shift, shift


def evaluated_mesh(ob):
    """The mesh the GLB will actually CARRY -- modifiers evaluated, as `export_apply=True` does.

    Added 2026-09-13 because the old measurements read the cage. With a live Subdivision or Bevel
    modifier the printed triangle count was the un-subdivided figure while the file carried the
    subdivided one, the topology gates inspected geometry that was never exported, and the
    "unapplied modifiers" gate then failed the build rather than let any of that ship. The three
    together made an iterative block-out-then-refine workflow impossible: every modifier had to be
    applied before the figure could be exported at all, so a subdivision cage could never be kept
    live and adjusted.

    Measure the evaluated mesh and all three problems go away at once -- the count is honest, the
    gates inspect the artifact, and modifiers become a reported fact instead of a failure. The
    caller must `to_mesh_clear()` the object it passed.
    """
    depsgraph = bpy.context.evaluated_depsgraph_get()
    return ob.evaluated_get(depsgraph).to_mesh()


def triangles(ob):
    """The REAL triangle count, from Blender's own triangulation.

    This was `len(polygons) * 2`, which assumes every face is a quad. That was true
    while the model was boxes and silently under-reports the moment topology is mixed
    -- which is exactly when a triangle budget starts mattering. Round 7 makes the
    budget a build gate, so the count has to be the one the GLB will carry.
    """
    me = evaluated_mesh(ob)
    me.calc_loop_triangles()
    count = len(me.loop_triangles)
    ob.to_mesh_clear()
    return count


def check_topology(ob, originals):
    """The game-mesh guarantee that replaced the style clauses on 2026-09-12.

    Wolf's ruling lifted flat faces, flat shading, bevels, subdivision and smooth
    normals -- none of them is tested any more, and rotation never was the thing that
    guarded the look. What stays is what a mesh needs in order to be rigged, skinned
    and shipped, plus the triangle budget.

    Deliberately NOT tested, because no cheap test is honest: interior geometry, and
    UV island overlap. Both are review items, judged by eye. A gate that cannot
    actually detect its subject is worse than no gate -- it certifies.
    """
    me = evaluated_mesh(ob)
    bm = bmesh.new()
    bm.from_mesh(me)

    ngons = sum(1 for f in bm.faces if len(f.verts) > 4)
    loose_verts = sum(1 for v in bm.verts if not v.link_edges)
    loose_edges = sum(1 for e in bm.edges if not e.link_faces)
    nonmanifold = sum(1 for e in bm.edges if len(e.link_faces) > 2)
    degenerate = sum(1 for f in bm.faces if f.calc_area() < AREA_EPS_M2)

    # Two faces sharing an edge must traverse it in OPPOSITE directions. If they
    # traverse it the same way, one of them is wound backwards.
    flipped = 0
    for e in bm.edges:
        if len(e.link_faces) != 2:
            continue
        walked = []
        for f in e.link_faces:
            for lp in f.loops:
                if lp.edge is e:
                    walked.append((lp.vert.index, lp.link_loop_next.vert.index))
                    break
        if len(walked) == 2 and walked[0] == walked[1]:
            flipped += 1

    bm.free()
    uv_layers = len(me.uv_layers)
    ob.to_mesh_clear()

    return {
        "n-gons": ngons,
        "non-manifold edges": nonmanifold,
        "loose verts": loose_verts,
        "loose edges": loose_edges,
        "degenerate faces": degenerate,
        "flipped winding": flipped,
        "missing UV layer": 0 if uv_layers else 1,
    }


def modifier_summary(originals):
    """Which modifiers are live, as a fact to report rather than a build failure.

    This was a GATE, and it had to be while the counts above read the cage: an unapplied
    Subdivision made the triangle figure a lie. The counts read the evaluated mesh now, so a live
    modifier is honest -- and forbidding them forbade the block-out-then-refine workflow. An
    Armature modifier was always correct to have; applying it would bake the rest pose into the
    vertices and throw the skin away.
    """
    live = [(o.name, m.type) for o in originals for m in o.modifiers if m.type != 'ARMATURE']
    return live


def glb_facts(path):
    """What the written GLB actually carries: its image names, and its skin's joint names.

    Read back out of the artifact.

    Round 7 shipped with image `r7` pointing at an absolute `D:/...` path and nothing packed, so
    off the authoring machine it resolved to nothing, the glTF exporter dropped the material's
    texture entirely -- no images, no textures, no samplers, no baseColorTexture -- and this
    script still printed `texture image r7` and exited 0, because that line reports the
    DATABLOCK'S NAME. A name is not data. The only honest subject for the gate is the file.
    """
    with open(path, "rb") as handle:
        data = handle.read()
    offset, images, joints, bounds = 12, [], [], (None, None)
    while offset + 8 <= len(data):
        length, kind = struct.unpack_from("<II", data, offset)
        if kind == 0x4E4F534A:
            document = json.loads(data[offset + 8:offset + 8 + length].decode("utf-8"))
            images = [image.get("name", "<unnamed>") for image in document.get("images", [])]
            primitive = document["meshes"][0]["primitives"][0]
            position = document["accessors"][primitive["attributes"]["POSITION"]]
            bounds = (position.get("min"), position.get("max"))
            nodes = document.get("nodes", [])
            joints = sorted(
                nodes[index].get("name", "<unnamed>")
                for skin in document.get("skins", [])
                for index in skin.get("joints", [])
            )
            break
        offset += 8 + length
    return images, joints, bounds


def main():
    for ob in list(bpy.data.objects):
        if ob.type in {'CAMERA', 'LIGHT'}:
            bpy.data.objects.remove(ob, do_unlink=True)

    if bpy.context.view_layer.objects.active is None:
        bpy.context.view_layer.objects.active = parts()[0]
    if bpy.context.object and bpy.context.object.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')

    arm = armature()
    originals = parts()
    for ob in originals:
        ob.hide_set(False)
        ob.hide_viewport = False
        ob.hide_render = False

    joined = flatten(originals)
    lo, hi, shift = seat_on_origin(joined)
    topology = check_topology(joined, originals)
    modifiers = modifier_summary(originals)
    tris = triangles(joined)

    # Re-bind the skin the join threw away, and move the skeleton by the SAME shift the vertices
    # took. `seat_on_origin` edits vertex coordinates; bones live in the armature, so without
    # this the joints sit wherever the figure used to be. `flatten` deliberately drops parenting
    # to bake the socket transforms, which is why the binding is remade here rather than kept.
    rig = None
    if arm is not None:
        arm.location = arm.location + shift
        joined.modifiers.new("Armature", 'ARMATURE').object = arm
        bpy.context.view_layer.update()
        rig = check_rig(joined, arm)

    materials = {slot.material for slot in joined.material_slots if slot.material}
    images = {n.image for m in materials if m.use_nodes
              for n in m.node_tree.nodes if n.type == 'TEX_IMAGE' and n.image}

    # glTF CLAMP_TO_EDGE, which the asset contract's sampler clause asks for and a packed set of
    # UV islands needs: under Blender's default REPEAT the far edge of the map bleeds into an
    # island sitting on the border. Forced here rather than in the .blend so no future round can
    # author it away. Blender's 'EXTEND' is glTF's CLAMP_TO_EDGE.
    for material in materials:
        if not material.use_nodes:
            continue
        for node in material.node_tree.nodes:
            if node.type == 'TEX_IMAGE':
                node.extension = 'EXTEND'

    # only the joined object -- and the skeleton it is bound to -- reaches the exporter
    bpy.ops.object.select_all(action='DESELECT')
    joined.select_set(True)
    if arm is not None:
        arm.select_set(True)
    bpy.context.view_layer.objects.active = joined

    os.makedirs(OUT_DIR, exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=OUT_PATH,
        export_format='GLB',
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_materials='EXPORT',
        export_image_format='AUTO',
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_skins=True,
        export_animations=False,
    )

    embedded, joints, bounds = glb_facts(OUT_PATH)
    size = (hi.x - lo.x, hi.y - lo.y, hi.z - lo.z)
    print("")
    print("EXPORT %s" % OUT_PATH)
    print("  parts joined      %d -> 1 mesh %r" % (len(originals), joined.data.name))
    print("  object / mesh     %s / %s" % (joined.name, joined.data.name))
    print("  materials         %s" % ", ".join(sorted(m.name for m in materials)))
    print("  texture image     %s   in the GLB: %s"
          % (", ".join(sorted(i.name for i in images)) or "<none>",
             ", ".join(embedded) or "<NONE>"))
    print("  triangles         %d  of %d budget" % (tris, TRI_BUDGET))
    print("  size m (X,Y,Z)    %.3f x %.3f x %.3f" % size)
    print("  blender min Z     %.6f   (glTF min Y)" % lo.z)
    print("  blender centre XY %.6f, %.6f   (glTF centre X, Z)"
          % ((lo.x + hi.x) / 2.0, (lo.y + hi.y) / 2.0))
    print("  topology          %s"
          % "   ".join("%s %d" % (k, v) for k, v in topology.items()))
    print("  live modifiers    %s"
          % (", ".join("%s:%s" % row for row in modifiers) or "none"))
    if rig is None:
        print("  rig               <NONE -- unrigged figure>")
    else:
        print("  rig               %s   joint names in the GLB: %s"
              % ("   ".join("%s %d" % (k, v) for k, v in rig.items()),
                 ", ".join(joints) or "<NONE>"))
    print("  GLB min/max       %s / %s   (glTF axes: X, Y up, Z)"
          % (bounds[0], bounds[1]))
    print("  bytes             %d" % os.path.getsize(OUT_PATH))

    # The seating clause, asserted on the ARTIFACT rather than on the intention. Every figure
    # above was measured in the scene; these are the numbers the exporter itself wrote into the
    # GLB's POSITION accessor, and they are what `check_asset.py` will read.
    if bounds[0] is None or bounds[1] is None:
        raise SystemExit("export: the GLB carries no POSITION bounds to check")
    low, high = bounds
    seating = {
        "min Y": low[1],
        "centre X": (low[0] + high[0]) / 2.0,
        "centre Z": (low[2] + high[2]) / 2.0,
    }
    off = {k: v for k, v in seating.items() if abs(v) > 1e-6}
    if off:
        raise SystemExit(
            "export: seating gate failed on the GLB's own bounds -- %s. The figure measured "
            "clean in the scene, so the geometry moved between the measurement and the file."
            % ", ".join("%s %.6f" % (k, v) for k, v in off.items()))

    if rig is not None:
        wrong = {k: v for k, v in rig.items() if k != "joints" and v}
        if wrong:
            raise SystemExit("export: rig gate failed -- %s"
                             % ", ".join("%s %d" % (k, v) for k, v in wrong.items()))
        if sorted(JOINTS) != joints:
            raise SystemExit(
                "export: the armature is correct and the GLB's skin is not -- joints in the "
                "file: %s. The skin is what the game binds to; a rig that stops at the .blend "
                "is not a rig." % (", ".join(joints) or "<NONE>"))

    if images and not embedded:
        raise SystemExit(
            "export: the material carries %d image(s) and the GLB embeds NONE -- the texture "
            "did not reach the artifact. The usual cause is an unpacked external path that does "
            "not resolve on this machine; pack it into the .blend (File > External Data > Pack "
            "Resources) so the source reproduces the export anywhere." % len(images))

    broken = {k: v for k, v in topology.items() if v}
    if broken:
        raise SystemExit("export: topology gate failed -- %s"
                         % ", ".join("%s %d" % (k, v) for k, v in broken.items()))
    if tris > TRI_BUDGET:
        raise SystemExit("export: %d triangles exceeds the %d budget" % (tris, TRI_BUDGET))


if __name__ == "__main__":
    main()
