"""Export SM_VoxelDwarf_Miner01 from the .blend to a GLB.

ONE COMMAND, from the repo root:

    blender --background src-assets/blender/SM_VoxelDwarf_Miner01.blend \
            --python src-assets/blender/export_dwarf.py

Writes src-assets/export/SM_VoxelDwarf_Miner01.glb (gitignored scratch). The
runtime slot assets/gltf/ is promoted by the operator and is never written here.

WHY THIS EXISTS. From round 4 the .blend is the SOURCE OF TRUTH and this script is
the only sanctioned way to get a binary out of it. The older finishing condition --
"the committed generator regenerates the committed GLB exactly" -- retired with that
change: a hand-modelled mesh cannot be regenerated byte-identically from a script,
and faking it by dumping tables would be a lie. What replaces it is this: the export
is repeatable from the committed .blend, and check_asset.py plus the r4 revision
token police the result.

WHAT IT ENFORCES, because the .blend is authored part-by-part and the contract wants
one object:
  * every mesh part is joined into ONE mesh, ONE material, ONE palette image;
  * the figure is centred in Blender X and Y and set to min Z = 0, which after the
    Z-up -> Y-up conversion is the contract's "min Y = 0, centred in X and Z";
  * sockets, cameras and lights never reach the GLB;
  * the mesh is fit to rig and ship -- no n-gons, manifold, no loose or degenerate
    geometry, consistent winding, UVs present, no unapplied modifiers, and at most
    TRI_BUDGET triangles. The style clauses (axis-aligned, then flat-and-planar) were
    both lifted by Wolf on 2026-09-12: shading and curvature are the artist's call;
  * the object and mesh datablocks carry the revision, so a stale binary announces
    itself. The revision lives in the datablock names INSIDE the .blend, not in any
    filename -- there is exactly one place to bump it.
"""

import os
import sys

import bmesh
import bpy
from mathutils import Vector

REV = "r7"        # each round bumps this, and it is the ONLY line to change here
ASSET = "SM_VoxelDwarf_Miner01"
COLLECTION = f"{ASSET}_{REV}"
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "export")
OUT_PATH = os.path.join(OUT_DIR, f"{ASSET}.glb")
TRI_BUDGET = 4000     # LOD0 ceiling, a build gate since round 7
AREA_EPS_M2 = 1e-10   # a face smaller than this is degenerate, not geometry


def parts():
    """Every mesh part of the figure, in a stable order."""
    coll = bpy.data.collections.get(COLLECTION)
    if coll is None:
        raise SystemExit(f"export: collection {COLLECTION!r} not found in this .blend")
    found = sorted((o for o in coll.objects if o.type == 'MESH'), key=lambda o: o.name)
    if not found:
        raise SystemExit(f"export: collection {COLLECTION!r} holds no mesh parts")
    return found


def flatten(originals):
    """Copy every part, drop its socket parenting, and join the copies into one mesh."""
    bpy.ops.object.select_all(action='DESELECT')
    copies = []
    for ob in originals:
        dup = ob.copy()
        dup.data = ob.data.copy()
        dup.matrix_world = ob.matrix_world.copy()   # bake the socket transform in
        dup.parent = None
        bpy.context.scene.collection.objects.link(dup)
        copies.append(dup)

    for dup in copies:
        dup.select_set(True)
    bpy.context.view_layer.objects.active = copies[0]
    bpy.ops.object.join()

    joined = bpy.context.view_layer.objects.active
    joined.name = f"{ASSET}_{REV}"
    joined.data.name = f"{ASSET}_{REV}"
    return joined


def seat_on_origin(ob):
    """Centre in X and Y, stand on Z = 0 -- the contract's invariant, in Blender axes."""
    bpy.context.view_layer.update()
    lo = Vector((1e9, 1e9, 1e9))
    hi = Vector((-1e9, -1e9, -1e9))
    for v in ob.data.vertices:
        w = ob.matrix_world @ v.co
        lo = Vector(min(lo[i], w[i]) for i in range(3))
        hi = Vector(max(hi[i], w[i]) for i in range(3))
    shift = Vector((-(lo.x + hi.x) / 2.0, -(lo.y + hi.y) / 2.0, -lo.z))
    for v in ob.data.vertices:
        v.co = v.co + shift
    ob.location = (0.0, 0.0, 0.0)
    bpy.context.view_layer.update()
    return lo + shift, hi + shift


def triangles(ob):
    """The REAL triangle count, from Blender's own triangulation.

    This was `len(polygons) * 2`, which assumes every face is a quad. That was true
    while the model was boxes and silently under-reports the moment topology is mixed
    -- which is exactly when a triangle budget starts mattering. Round 7 makes the
    budget a build gate, so the count has to be the one the GLB will carry.
    """
    ob.data.calc_loop_triangles()
    return len(ob.data.loop_triangles)


def check_topology(ob, originals):
    """The game-mesh guarantee that replaced the style clauses on 2026-09-12.

    Wolf's ruling lifted flat faces, flat shading, bevels, subdivision and smooth
    normals -- none of them is tested any more, and rotation never was the thing that
    guarded the look. What stays is what a mesh needs in order to be rigged, skinned
    and shipped, plus the triangle budget.

    Deliberately NOT tested, because no cheap test is honest: interior geometry, and
    UV island overlap. Both are review items, judged by eye. A gate that cannot
    actually detect its subject is worse than no gate -- it certifies.
    """
    me = ob.data
    bm = bmesh.new()
    bm.from_mesh(me)

    ngons = sum(1 for f in bm.faces if len(f.verts) > 4)
    loose_verts = sum(1 for v in bm.verts if not v.link_edges)
    loose_edges = sum(1 for e in bm.edges if not e.link_faces)
    nonmanifold = sum(1 for e in bm.edges if len(e.link_faces) > 2)
    degenerate = sum(1 for f in bm.faces if f.calc_area() < AREA_EPS_M2)

    # Two faces sharing an edge must traverse it in OPPOSITE directions. If they
    # traverse it the same way, one of them is wound backwards.
    flipped = 0
    for e in bm.edges:
        if len(e.link_faces) != 2:
            continue
        walked = []
        for f in e.link_faces:
            for lp in f.loops:
                if lp.edge is e:
                    walked.append((lp.vert.index, lp.link_loop_next.vert.index))
                    break
        if len(walked) == 2 and walked[0] == walked[1]:
            flipped += 1

    bm.free()

    return {
        "n-gons": ngons,
        "non-manifold edges": nonmanifold,
        "loose verts": loose_verts,
        "loose edges": loose_edges,
        "degenerate faces": degenerate,
        "flipped winding": flipped,
        "missing UV layer": 0 if me.uv_layers else 1,
        "unapplied modifiers": sum(len(o.modifiers) for o in originals),
    }


def main():
    for ob in list(bpy.data.objects):
        if ob.type in {'CAMERA', 'LIGHT'}:
            bpy.data.objects.remove(ob, do_unlink=True)

    if bpy.context.view_layer.objects.active is None:
        bpy.context.view_layer.objects.active = parts()[0]
    if bpy.context.object and bpy.context.object.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')

    originals = parts()
    for ob in originals:
        ob.hide_set(False)
        ob.hide_viewport = False
        ob.hide_render = False

    joined = flatten(originals)
    lo, hi = seat_on_origin(joined)
    topology = check_topology(joined, originals)
    tris = triangles(joined)

    materials = {slot.material for slot in joined.material_slots if slot.material}
    images = {n.image for m in materials if m.use_nodes
              for n in m.node_tree.nodes if n.type == 'TEX_IMAGE' and n.image}

    # only the joined object reaches the exporter
    bpy.ops.object.select_all(action='DESELECT')
    joined.select_set(True)
    bpy.context.view_layer.objects.active = joined

    os.makedirs(OUT_DIR, exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=OUT_PATH,
        export_format='GLB',
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_materials='EXPORT',
        export_image_format='AUTO',
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_skins=False,
        export_animations=False,
    )

    size = (hi.x - lo.x, hi.y - lo.y, hi.z - lo.z)
    print("")
    print("EXPORT %s" % OUT_PATH)
    print("  parts joined      %d -> 1 mesh %r" % (len(originals), joined.data.name))
    print("  object / mesh     %s / %s" % (joined.name, joined.data.name))
    print("  materials         %s" % ", ".join(sorted(m.name for m in materials)))
    print("  texture image     %s" % ", ".join(sorted(i.name for i in images)))
    print("  triangles         %d  of %d budget" % (tris, TRI_BUDGET))
    print("  size m (X,Y,Z)    %.3f x %.3f x %.3f" % size)
    print("  blender min Z     %.6f   (glTF min Y)" % lo.z)
    print("  blender centre XY %.6f, %.6f   (glTF centre X, Z)"
          % ((lo.x + hi.x) / 2.0, (lo.y + hi.y) / 2.0))
    print("  topology          %s"
          % "   ".join("%s %d" % (k, v) for k, v in topology.items()))
    print("  bytes             %d" % os.path.getsize(OUT_PATH))

    broken = {k: v for k, v in topology.items() if v}
    if broken:
        raise SystemExit("export: topology gate failed -- %s"
                         % ", ".join("%s %d" % (k, v) for k, v in broken.items()))
    if tris > TRI_BUDGET:
        raise SystemExit("export: %d triangles exceeds the %d budget" % (tris, TRI_BUDGET))


if __name__ == "__main__":
    main()
